TaskCity/Controllers/TasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TaskCity.Models;

namespace TaskCity.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private TaskContext db = new TaskContext();

        // GET: Tasks
        public async Task<ActionResult> Index()
        {
            return View(db.GetTasksForUser(User.Identity.GetUserId()));
        }

        // GET: Tasks/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WTask wTask = await db.Tasks.FindAsync(id);
            if (wTask == null)
            {
                return HttpNotFound();
            }
            return View(wTask);
        }

        [HttpGet]
        public JsonResult GetSubCats(int? id)
        {
            return Json(new SelectList(db.GetSubCatsOf(id.Value), "Id", "Name"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCatInfo(int? id)
        {
            if (id == null)
                return new JsonResult();
            string result = db.GetCatInfo(id.Value);
            if (result == null)
                return Json(string.Empty, JsonRequestBehavior.AllowGet);

            return Json(db.GetCatInfo(id.Value), JsonRequestBehavior.AllowGet);
        }

        // GET: Tasks/Create
        public ActionResult Create()
        {
            ViewBag.CatItems = new SelectList(db.RootCats, "Id", "Name");
            ViewBag.SubCatItems = new SelectList(db.GetSubCatsOf(db.RootCats.ElementAt(0).Id), "Id", "Name");
            if (db.Tasks.Any())
            {
                var lastTask = db.Tasks.ToList().Last();
                var newTask = new WTask();
                newTask.Name = lastTask.Name;
                newTask.Phone = lastTask.Phone;
                newTask.Address = lastTask.Address;

                return View(newTask);
            }
            return View();
        }

        // POST: Tasks/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,UserId,CatId,SubCatId,Description,Address,Phone,Name")] WTask wTask)
        {
            if (ModelState.IsValid)
            {
                wTask.UserId = User.Identity.GetUserId();
                db.Tasks.Add(wTask);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CatItems = new SelectList(db.RootCats, "Id", "Name");
            ViewBag.SubCatItems = new SelectList(db.GetSubCatsOf(db.RootCats.ElementAt(0).Id), "Id", "Name");
            return View(wTask);
        }

        // GET: Tasks/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WTask wTask = await db.Tasks.FindAsync(id);
            if (wTask == null)
            {
                return HttpNotFound();
            }

            ViewBag.CatItems = new SelectList(db.RootCats, "Id", "Name");
            ViewBag.SubCatItems = new SelectList(db.GetSubCatsOf(db.RootCats.ElementAt(0).Id), "Id", "Name");

            return View(wTask);
        }

        // POST: Tasks/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,UserId,CatId,SubCatId,Description,Address,Phone,Name")] WTask wTask)
        {
            if (ModelState.IsValid)
            {
                wTask.UserId = User.Identity.GetUserId();
                db.Entry(wTask).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(wTask);
        }

        // GET: Tasks/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WTask wTask = await db.Tasks.FindAsync(id);
            if (wTask == null)
            {
                return HttpNotFound();
            }
            return View(wTask);
        }

        // POST: Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            WTask wTask = await db.Tasks.FindAsync(id);
            db.Tasks.Remove(wTask);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TaskCity/Views/Tasks/Create.cshtml
@model TaskCity.Models.WTask

@{
    ViewBag.Title = "Create";
}

<div class="container">
    <h2>Заполнение заявки</h2>
    <p>Пожалуйста, заполните все поля.</p>
    <hr />

    @using (Html.BeginForm("Create", "Tasks", FormMethod.Post, new { @class = "form-group", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "alert alert-danger" })

        <div class="form-group">
            @Html.Label("Задание:", new { @class = "col-sm-2 control-label" })
            @Html.DropDownListFor(x => x.CatId, (SelectList)ViewBag.CatItems, new { @class = "btn btn-default dropdown-toggle", style = "width: 250px", onchange = "OnSelectedCatChange(this,'GetSubCats')" }) 

            @Html.DropDownListFor(x => x.SubCatId, (SelectList)ViewBag.SubCatItems, "Не выбрано", new { @class = "btn btn-default dropdown-toggle", style = "width: 250px", id = "subcats_ddl", onchange = "UpdateCatInfoContent(this,'GetCatInfo')" })
        </div>

        <div style="width: 695px" class="alert alert-info" role="alert" id="catinfo" hidden=""></div>
        
        <div class="form-group form-inline">
            @Html.Label("Описание: ", new { @class = "col-sm-2 control-label" })
            @Html.TextAreaFor(x => x.Description, new { @class = "form-control", @placeholder = "Подробно расскажите, что нужно сделать", style = "width: 505px" })
        </div>
        <div class="form-group form-inline">
            @Html.Label("Адрес:", new { @class = "col-sm-2 control-label" })
            @Html.DropDownList("city", new[]
            {
                new SelectListItem() {Text = "Ростов-на-Дону"},
            }, new { @class = "btn btn-default dropdown-toggle", style = "width: 250px" })

            @Html.TextBoxFor(x => x.Address, new { @class = "form-control", @placeholder = "пример: Ленина 19/1, кв. 12", style = "width: 250px" })
        </div>
        <div class="form-group form-inline">
            @Html.Label("Телефон:", new { @class = "col-sm-2 control-label" })
            @Html.TextBoxFor(x => x.Phone, new { @class = "form-control", @placeholder = "+7928123456789", style = "width: 505px" })
        </div>
        <div class="form-group form-inline">
            @Html.Label("Обращение:", new { @class = "col-sm-2 control-label" })
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "пример: Фёдор Иванович", style = "width: 505px" })
        </div>

        <div class="form-group">
            <div class="text-left">
                <input type="submit" class="btn btn-default btn-lg" value="Создать" />
            </div>
        </div>
    }



    <div>
        <a href="@Url.Action("Index")"><span class="glyphicon glyphicon-chevron-left"></span> Назад</a>
    </div>
 </div>
@Scripts.Render("/Scripts/dropbox-selectsubcat-update.js")

TaskCity/Views/Tasks/Delete.cshtml
@model TaskCity.Models.WTask

@{
    ViewBag.Title = "Удаление задания";
}

<h2>Удаление</h2>

<h3>Вы действительно хотите удалить данное задание?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CatId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CatId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubCatId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubCatId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()


            <input type="submit" value="Удалить" class="btn btn-default" />
   
 
    }
    <br/>
    <a href="@Url.Action("Index")"><span class="glyphicon glyphicon-chevron-left"></span> Назад</a>
</div>

TaskCity/Views/Tasks/Details.cshtml
@model TaskCity.Models.WTask

@{
    ViewBag.Title = "Details";
}



<div class="container">
    <h2>Details</h2>
    <h4>WTask</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CatId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CatId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubCatId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubCatId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Index")"><span class="glyphicon glyphicon-chevron-left"></span> Назад</a> |
    <a href="@Url.Action("Edit", new { id = Model.Id })"><span class="glyphicon glyphicon-pencil"></span> Изменить</a>


</p>

TaskCity/Views/Tasks/Edit.cshtml
@model TaskCity.Models.WTask

@{
    ViewBag.Title = "Редактирование";
}

<div class="container">
    <h2>Редактирование</h2>
    <hr/>
    @using (Html.BeginForm("Edit", "Tasks", FormMethod.Post, new { @class = "form-group", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "alert alert-danger" })

        <div class="form-group">
            @Html.Label("Задание:", new { @class = "col-sm-2 control-label" })
            @Html.DropDownListFor(x => x.CatId, (SelectList)ViewBag.CatItems, new { @class = "btn btn-default dropdown-toggle", style = "width: 250px", onchange = "OnSelectedCatChange(this,'../GetSubCats')" }) 

            @Html.DropDownListFor(x => x.SubCatId, (SelectList)ViewBag.SubCatItems, "Не выбрано", new { @class = "btn btn-default dropdown-toggle", style = "width: 250px", id = "subcats_ddl", onchange = "UpdateCatInfoContent(this,'../GetCatInfo')" })
        </div>

        <div style="width: 695px" class="alert alert-info" role="alert" id="catinfo" hidden=""></div>
        
        <div class="form-group form-inline">
            @Html.Label("Описание: ", new { @class = "col-sm-2 control-label" })
            @Html.TextAreaFor(x => x.Description, new { @class = "form-control", @placeholder = "Подробно расскажите, что нужно сделать", style = "width: 505px" })
        </div>
        <div class="form-group form-inline">
            @Html.Label("Адрес:", new { @class = "col-sm-2 control-label" })
            @Html.DropDownList("city", new[]
            {
                new SelectListItem() {Text = "Ростов-на-Дону"},
            }, new { @class = "btn btn-default dropdown-toggle", style = "width: 250px" })

            @Html.TextBoxFor(x => x.Address, new { @class = "form-control", @placeholder = "пример: Ленина 19/1, кв. 12", style = "width: 250px" })
        </div>
        <div class="form-group form-inline">
            @Html.Label("Телефон:", new { @class = "col-sm-2 control-label" })
            @Html.TextBoxFor(x => x.Phone, new { @class = "form-control", @placeholder = "+7928123456789", style = "width: 505px" })
        </div>
        <div class="form-group form-inline">
            @Html.Label("Обращение:", new { @class = "col-sm-2 control-label" })
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control", @placeholder = "пример: Фёдор Иванович", style = "width: 505px" })
        </div>

        <div class="form-group">
            <div class="text-left">
                <input type="submit" class="btn btn-default btn-lg" value="Сохранить" />
            </div>
        </div>
    }



    <div>
        <a href="@Url.Action("Index")"><span class="glyphicon glyphicon-chevron-left"></span> Назад</a>
    </div>
</div>
@Scripts.Render("/Scripts/dropbox-selectsubcat-update.js")

TaskCity/Views/Tasks/Index.cshtml
@model IEnumerable<TaskCity.Models.WTask>

@{
    ViewBag.Title = "Index";
}

<h2>Список заданий</h2>

<p>
    <a href="@Url.Action("Create")"><span class="glyphicon glyphicon-plus-sign"></span> Добавить задание</a>
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CatId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubCatId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CatId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubCatId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            <div class="form-group">
                <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-default"><span class="glyphicon glyphicon-pencil"></span></a>
                <a href="@Url.Action("Details", new { id = item.Id })" class="btn btn-default"><span class="glyphicon glyphicon-info-sign"></span></a>
                <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-default"><span class="glyphicon glyphicon-remove-sign"></span></a>
            </div>
        </td>
    </tr>
}

</table>